TrackingRace/ViewModels/RunnerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TrackingRaceLibrary.Models;

namespace TrackingRace.ViewModels
{
    public class RunnerViewModel
    {
        public int? Id { get; set; }

        [DisplayName("First Name:")]
        [Required(ErrorMessage = "The First Name field is required")]
        [StringLength(20)]
        public string FName { get; set; }

        [DisplayName("Last Name:")]
        [Required(ErrorMessage = "The Last Name field is required")]
        [StringLength(20)]
        public string LName { get; set; }
        //public string Address { get; set; }
        //public string City { get; set; }
        //public string StateId { get; set; }
        //public int ZipCode { get; set; }

        [DisplayName("Size:")]
        [Required(ErrorMessage = "The Size field is required")]
        public int SizeId { get; set; }

        [DisplayName("Gender:")]
        [Required(ErrorMessage = "The Gender field is required")]
        public string GenderId { get; set; }

        [DisplayName("Date of Birthday:")]
        [Required(ErrorMessage = "The Date of Birthday field is required")]
        [DataType(DataType.Date)]
        public DateTime DOB { get; set; }

        [DisplayName("Email:")]
        [Required(ErrorMessage = "The Email field is required")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }

        [DisplayName("Phone:")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        public string Phone { get; set; }


        public bool IsTrue => true;

        [Required]
        [DisplayName("I agree to the TrackingRace Agreement and Waiver")]
        [Compare(nameof(IsTrue), ErrorMessage = "I agree to the TrackingRace Agreement and Waiver")]
        public bool WaiverAgreement { get; set; }

        public virtual List<RaceViewModel> Races { get; set; }

        //Support Properties 
        [Required(ErrorMessage = "Please select a Race")]
        public int RaceId { get; set; }
        public string RaceName { get; set; }

        [DisplayName("Size:")]
        public string SizeName { get; set; }
        public Size Size { get; set; }


        [DisplayName("Gender:")]
        public string GenderName { get; set; }
        public Gender Gender { get; set; }


    }
}

TrackingRace/Controllers/RunnerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackingRace.ViewModels;
using TrackingRaceLibrary.Data;
using TrackingRaceLibrary.Models;

namespace TrackingRace.Controllers
{
    public class RunnerController : Controller
    {
        private Context _context = null;

        public RunnerController()
        {
            _context = new Context();
        }

        private bool _disposed = false;

        protected override void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            if (disposing)
            {
                _context.Dispose();
            }

            _disposed = true;

            base.Dispose(disposing);
        }


        // GET: Runner
        public ActionResult Index()
        {
            ViewBag.Title = "Work With Runners";

            using (var context = new Context())
            {
                var runnerList = new RunnerListViewModel
                {
                    Runners = context.Runners.Select(p => new RunnerViewModel
                    {
                        Id = p.Id,
                        FName = p.FName,
                        LName = p.LName,
                        Size = p.Size,
                        Gender = p.Gender,
                        DOB = p.DOB,
                        Email = p.Email,
                        Phone = p.Phone,
                        WaiverAgreement = p.WaiverAgreement


                    }).ToList()
                };
                runnerList.TotalRuners = runnerList.Runners.Count;

                return View(runnerList);
            }
        }
        
        //Start the Sign-Up proccess
        public ActionResult Signup(int? raceId)
        {

            ViewBag.Title = "Signup Runner";
            var runnerViewModel = new RunnerViewModel();
            runnerViewModel.DOB = DateTime.Now.Date;
            if (raceId != null)
            {
                //Adding Race to RunnerViewModel
                runnerViewModel.RaceId = raceId.Value;
                var race = _context.Races.SingleOrDefault(r => r.Id == raceId);
                runnerViewModel.RaceName = race.Name;
                ViewBag.Race = race;
            }
            else
            {
                ViewBag.SelectRace = new SelectList(_context.Races, "Id", "Name");
            }

            ViewBag.SelectGender = new SelectList(_context.Gender, "Id", "Name");
            ViewBag.SelectSize = new SelectList(_context.Sizes, "Id", "Name");

            return View("SignupEdit", runnerViewModel);
        }
        
        //Validate Runner info before submit payment
        [HttpPost]
        public ActionResult Signup(RunnerViewModel runnerViewModel)
        {
            if (ModelState.IsValid)
            {
                var race = _context.Races.SingleOrDefault(r => r.Id == runnerViewModel.RaceId);
                runnerViewModel.Gender = _context.Gender.SingleOrDefault(g => g.Id == runnerViewModel.GenderId);
                runnerViewModel.Size = _context.Sizes.SingleOrDefault(s => s.Id == runnerViewModel.SizeId);
                ViewBag.RaceName = race.Name;
                return View("CheckOut", runnerViewModel);
            }
            return View("SignupEdit", runnerViewModel);
        }

        
        public ActionResult ReviewInfo(RunnerViewModel runnerViewModel)
        {
            ViewBag.SelectRace = new SelectList(_context.Races, "Id", "Name");
            ViewBag.SelectGender = new SelectList(_context.Gender, "Id", "Name");
            ViewBag.SelectSize = new SelectList(_context.Sizes, "Id", "Name");
            return View("SignupEdit", runnerViewModel);
        }

        //Saving User
        [HttpPost]
        public ActionResult SheckOut(RunnerViewModel runnerViewModel)
        {
            using (var context = new Context())
            {
                var runner = new Runner
                {
                    FName = runnerViewModel.FName,
                    LName = runnerViewModel.LName,
                    SizeId = runnerViewModel.SizeId,
                    GenderId = runnerViewModel.GenderId,
                    DOB = runnerViewModel.DOB,
                    Email = runnerViewModel.Email,
                    Phone = runnerViewModel.Phone,
                    WaiverAgreement = runnerViewModel.WaiverAgreement,
                };

                context.Runners.Add(runner);
                context.SaveChanges();

                var raceRunner = new RaceRunner
                {
                    RaceId = runnerViewModel.RaceId,
                    RunnerId = runner.Id
                };

                context.RaceRunners.Add(raceRunner);
                context.SaveChanges();

                TempData["Message"] = runner.FName + " " + runner.LName + " was successfully registered!";
            };

            return RedirectToAction("Index", "Home");
        }
    }
}

TrackingRace/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackingRace.ViewModels;
using TrackingRaceLibrary.Data;
using TrackingRaceLibrary.Models;

namespace TrackingRace.Controllers
{
    public class StateController : Controller
    {
        private Context _context = null;

        public StateController()
        {
            _context = new Context();
        }

        // GET: State
        public ActionResult Index()
        {
            using (var context = new Context())
            {
                var stateList = new StateListViewModel
                {
                    //Convert each State to a StateViewModel
                    States = context.States.Select(p => new StateViewModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        Acronym = p.Acronym
                    }).ToList()
                };
                stateList.TotalStates = stateList.States.Count;
                ViewBag.Title = "Work With States";
                return View(stateList);
            }
        }

        //Detail
        public ActionResult Detail(int id)
        {
            using (var context = new Context())
            {
                var state = context.States.SingleOrDefault(p => p.Id == id);
                if (state != null)
                {
                    var stateViewModel = new StateViewModel
                    {
                        Id = state.Id,
                        Name = state.Name,
                        Acronym = state.Acronym
                    };
                    ViewBag.Title = "Detail " + stateViewModel.Name;
                    return View(stateViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        //Add
        public ActionResult Add()
        {
            ViewBag.Title = "Add State";
            var stateViewModel = new StateViewModel();

            return View("AddEdit", stateViewModel);
        }

        [HttpPost]
        public ActionResult Add(StateViewModel stateViewModel)
        {
            //ValdateState(stateViewModel);

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var state = new State
                    {
                        Name = stateViewModel.Name,
                        Acronym = stateViewModel.Acronym
                    };

                    context.States.Add(state);
                    context.SaveChanges();
                }

                TempData["Message"] = "Your state was successfully added!";
                return RedirectToAction("Index");
            }

            return View(stateViewModel);
        }

        //Edit
        public ActionResult Edit(int id)
        {
            using (var context = new Context())
            {
                var state = context.States.SingleOrDefault(p => p.Id == id);
                if (state != null)
                {
                    var stateViewModel = new StateViewModel
                    {
                        Id = state.Id,
                        Name = state.Name,
                        Acronym = state.Acronym
                    };
                    return View("AddEdit", stateViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        [HttpPost]
        public ActionResult Edit(StateViewModel stateViewModel)
        {
            //ValdateState(stateViewModel);

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var state = context.States.SingleOrDefault(p => p.Id == stateViewModel.Id);

                    if(state != null)
                    {
                        state.Name = stateViewModel.Name;
                        state.Acronym = stateViewModel.Acronym;

                        TempData["Message"] = "Your state was successfully updated!";
                        context.SaveChanges();
                        return RedirectToAction("Index");
                    };
                } 
            }
            return View(stateViewModel);
        }


        //Delete
        [HttpPost]
        public ActionResult Delete(StateViewModel stateViewModel)
        {
            using (var context = new Context())
            {
                var state = context.States.SingleOrDefault(p => p.Id == stateViewModel.Id);
                if (state != null)
                {
                    TempData["Message"] = state.Name + " state was successfully deleted!";
                    context.States.Remove(state);
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            return new HttpNotFoundResult();
        }
        

        //private void ValdateState(StateViewModel stateViewModel)
        //{
        //    if (ModelState.IsValidField("Name"))
        //    {
        //        ModelState.AddModelError("Name", "The Name field cannot be empty");
        //    }

        //    if (ModelState.IsValidField("Acronym"))
        //    {
        //        ModelState.AddModelError("Acronym", "The Acronym field cannot be empty");
        //    }
        //}





        //private bool _disposed = false;

        //protected override void Dispose(bool disposing)
        //{
        //    if (_disposed)
        //        return;

        //    if (disposing)
        //    {
        //        _context.Dispose();
        //    }

        //    _disposed = true;

        //    base.Dispose(disposing);
        //}
    }
}

TrackingRace/Views/Runner/CheckOut.cshtml
@model TrackingRace.ViewModels.RunnerViewModel
@Html.Partial("_Message")

@{
    var isEditMode = Model.Id != null;
    ViewBag.Title = isEditMode ? "Edit" : "Check Out";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-sm-12 col-xs-10">


        @using (Html.BeginForm("SheckOut", "Runner", Model))
        {
            @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-dismissible alert-danger"})

            <div class="form-row">
                <div class="form-group col-6">
                    <label class="float-right">Race: </label>
                </div>
                <div class="form-group col-6">
                    <label>@ViewBag.RaceName</label>
                </div>
            </div>


            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.FName, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.FName)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.LName, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.LName)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.SizeName, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.Size.Name)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.GenderName, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.Gender.Name)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.DOB, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.DOB)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.Email, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.Email)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    @Html.LabelFor(m => m.Phone, new { @class = "float-right" })
                </div>
                <div class="form-group col-6">
                    @Html.DisplayFor(m => m.Phone)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                </div>
                <div class="form-group col-md-6">
                    @Html.CheckBoxFor(m => m.WaiverAgreement, new { @disabled = "disabled" }) @Html.DisplayNameFor(m => m.WaiverAgreement)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-6">
                    <button type="submit" class="btn btn-primary float-right">Check Out</button>
                </div>
                <div class="form-group col-6">
                    @Html.ActionLink("Cancel", "ReviewInfo", Model, new { @class = "btn btn-secondary" })
                </div>
            </div>
        }
    </div>
</div>

TrackingRace/Views/Runner/Index.cshtml
@model TrackingRace.ViewModels.RunnerListViewModel

@Html.Partial("_Message")

<div class="d-inline-block">
    <h2>@ViewBag.Title</h2>
</div>

<div class="d-inline-block float-right">
    <a href="@Url.Action("Signup")" class="btn btn-primary btn">Add</a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th class="d-none d-md-table-cell">Gender</th>
            <th class="d-none d-md-table-cell">Size</th>
            <th class="d-none d-md-table-cell">DOB</th>
            <th class="d-none d-md-table-cell">Phone</th>
            <th class="d-none d-md-table-cell">Email</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Runners.Count; i++)
        {
        <tr>
            <td>@Model.Runners[i].FName @Model.Runners[i].LName</td>
            <td class="d-none d-md-table-cell">@Model.Runners[i].Gender.Name</td>
            <td class="d-none d-md-table-cell">@Model.Runners[i].Size.Name</td>
            <td class="d-none d-md-table-cell">@Model.Runners[i].DOB.ToShortDateString()</td>
            <td class="d-none d-md-table-cell">@Model.Runners[i].Phone</td>
            <td class="d-none d-md-table-cell">@Model.Runners[i].Email</td>
            <td>
                <div class="float-right">
                    @*<a href="@Url.Action("Detail", new { id = Model.Races[i].Id })" class="btn btn-primary btn-xs margin-right">
                    <span class="glyphicon glyphicon-info-sign"></span><span class="hidden-xs"> Detail</span>
                </a>*@

                    @*<div class="btn-group" role="group" aria-label="Basic example">
                    <a href="@Url.Action("Edit", new { id = Model.Races[i].Id })" class="btn btn-secondary btn-xs margin-right">
                        <span class="hidden-xs"> Edit</span>
                    </a>
                    <a href="@Url.Action("Detail", new { id = Model.Races[i].Id })" class="btn btn-secondary btn-xs margin-right">
                        <span class="hidden-xs"> Detail</span>
                    </a>
                    <a data-toggle="modal" href="@("#deleteRaceModal" + i)" class="btn btn-danger btn-xs margin-right">
                        <span class="hidden-xs"> Delete</span>
                    </a>
                </div>

                <div class="modal fade" id="@("deleteRaceModal" + i)" tabindex="-1" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            @using (Html.BeginForm("Delete", "State"))
                            {
                                <input type="hidden" value="@Model.Races[i].Id" name="Id" />
                                <div class="modal-header">
                                    <h4 class="modal-title">Delete @Model.Races[i].Name</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete @Model.Races[i].Name?
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">Yes</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>*@
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>

TrackingRace/Views/Runner/PayPalCheckOut.cshtml
@using System.Configuration
<body>
    <form action="@ConfigurationManager.AppSettings["urlSubmitPayment"]">
        <input type="" name="cmd" value="_xclick" />@*" _cart" />*@
        <input type="" name="upload" value="1" />
        <input type="" name="return" value="@ConfigurationManager.AppSettings["urlReturn"]" />
        <input type="" name="business" value="@ConfigurationManager.AppSettings["accountBusiness"]" />


        <input type="" name="@Url.Content("item_name")" value="Shake a Leg - Race" />
        <input type="" name="@Url.Content("amount")" value="35" />
    </form>
</body>

TrackingRace/Views/Runner/SignupEdit.cshtml
@model TrackingRace.ViewModels.RunnerViewModel

@Html.Partial("_Message")

@{
    var isEditMode = Model.Id != null;
    ViewBag.Title = isEditMode ? "Edit" : "Sign Up";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-sm-12 col-xs-10">
        @using (Html.BeginForm("Signup", "Runner"))
        {
            @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-dismissible alert-danger" })

            if (ViewBag.Race != null)
            {
                //var race = ViewBag.Race;
                Model.RaceId = ViewBag.Race.Id;
                @Html.HiddenFor(m => m.RaceId)
                <legend>Race: @ViewBag.Race.Name</legend>
            }
            else
            {
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <legend>Race: </legend>
                        @Html.DropDownListFor(m => m.RaceId, (SelectList)ViewBag.SelectRace, "", new { @class = "form-control" })
                    </div>
                </div>
            }

            @Html.HiddenFor(m => m.Id)

            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.FName)
                    @Html.TextBoxFor(m => m.FName, new { @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.LName)
                    @Html.TextBoxFor(m => m.LName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    @Html.LabelFor(m => m.SizeId)
                    @Html.DropDownListFor(m => m.SizeId, (SelectList)ViewBag.SelectSize, "", new { @class = "form-control" })
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(m => m.GenderId)
                    @Html.DropDownListFor(m => m.GenderId, (SelectList)ViewBag.SelectGender, "", new { @class = "form-control" })
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(m => m.DOB)
                    @Html.TextBoxFor(m => m.DOB, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker" })
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.Phone)
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(m => m.WaiverAgreement) @Html.DisplayNameFor(m => m.WaiverAgreement)
                        @Html.Hidden(nameof(Model.IsTrue), "true")
                    </label>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">@(isEditMode ? "Save" : "Sign Up")</button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>