TrackingRace/ViewModels/SizeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrackingRace.ViewModels
{
    public class SizeViewModel
    {
        public int? Id { get; set; }

        [StringLength(2)]
        [DisplayName("Acronym:")]
        [Required(ErrorMessage = "The Acronym field is required")]
        public string Acronym { get; set; }

        [StringLength(10)]
        [DisplayName("Name:")]
        [Required(ErrorMessage = "The Name field is required")]
        public string Name { get; set; }
    }
}

TrackingRace/Controllers/SizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackingRace.ViewModels;
using TrackingRaceLibrary.Data;
using TrackingRaceLibrary.Models;

namespace TrackingRace.Controllers
{
    public class SizeController : Controller
    {
        // GET: size
        public ActionResult Index()
        {
            using (var context = new Context())
            {
                var sizeList = new SizeListViewModel
                {
                    //Convert each size to a SizeViewModel
                    Sizes = context.Sizes.Select(p => new SizeViewModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        Acronym = p.Acronym
                    }).ToList()
                };
                sizeList.TotalSizes = sizeList.Sizes.Count;
                ViewBag.Title = "Work With Sizes";
                return View(sizeList);
            }
        }

        //Detail
        public ActionResult Detail(int id)
        {
            using (var context = new Context())
            {
                var size = context.Sizes.SingleOrDefault(p => p.Id == id);
                if (size != null)
                {
                    var SizeViewModel = new SizeViewModel
                    {
                        Id = size.Id,
                        Name = size.Name,
                        Acronym = size.Acronym
                    };
                    ViewBag.Title = "Detail " + SizeViewModel.Name;
                    return View(SizeViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        //Add
        public ActionResult Add()
        {
            ViewBag.Title = "Add size";
            var SizeViewModel = new SizeViewModel();

            return View("AddEdit", SizeViewModel);
        }

        [HttpPost]
        public ActionResult Add(SizeViewModel SizeViewModel)
        {
            //Valdatesize(SizeViewModel);

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var size = new Size
                    {
                        Name = SizeViewModel.Name,
                        Acronym = SizeViewModel.Acronym
                    };

                    context.Sizes.Add(size);
                    context.SaveChanges();
                }

                TempData["Message"] = "Your size was successfully added!";
                return RedirectToAction("Index");
            }

            return View(SizeViewModel);
        }

        //Edit
        public ActionResult Edit(int id)
        {
            using (var context = new Context())
            {
                var size = context.Sizes.SingleOrDefault(p => p.Id == id);
                if (size != null)
                {
                    var SizeViewModel = new SizeViewModel
                    {
                        Id = size.Id,
                        Name = size.Name,
                        Acronym = size.Acronym
                    };
                    return View("AddEdit", SizeViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        [HttpPost]
        public ActionResult Edit(SizeViewModel SizeViewModel)
        {
            //Valdatesize(SizeViewModel);

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var size = context.Sizes.SingleOrDefault(p => p.Id == SizeViewModel.Id);

                    if (size != null)
                    {
                        size.Name = SizeViewModel.Name;
                        size.Acronym = SizeViewModel.Acronym;

                        TempData["Message"] = "Your size was successfully updated!";
                        context.SaveChanges();
                        return RedirectToAction("Index");
                    };
                }
            }
            return View(SizeViewModel);
        }


        //Delete
        [HttpPost]
        public ActionResult Delete(SizeViewModel SizeViewModel)
        {
            using (var context = new Context())
            {
                var size = context.Sizes.SingleOrDefault(p => p.Id == SizeViewModel.Id);
                if (size != null)
                {
                    TempData["Message"] = size.Name + " size was successfully deleted!";
                    context.Sizes.Remove(size);
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            return new HttpNotFoundResult();
        }
    }
}

TrackingRace/Views/Size/AddEdit.cshtml
@model TrackingRace.ViewModels.SizeViewModel

@Html.Partial("_Message")

@{
    var isEditMode = Model.Id != null;
    ViewBag.Title = isEditMode ? "Edit" : "Add Size";
}

<h2>@ViewBag.Title</h2>


<div class="row">
    <div class="col-sm-6 col-xs-10">
        @using (Html.BeginForm(isEditMode ? "Edit" : "Add", "Size"))
        {
            @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-dismissible alert-danger" })

            @Html.HiddenFor(m => m.Id)
            <div class="form-group col-md-10">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
            <div class="form-group col-md-2">
                @Html.LabelFor(m => m.Acronym)
                @Html.TextBoxFor(m => m.Acronym, new { @class = "form-control" })
            </div>

            <div class="form-group col-md-10 mt-4">
                <button type="submit" class="btn btn-primary">@(isEditMode ? "Save" : "Add")</button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

TrackingRace/Views/Size/Detail.cshtml
@model TrackingRace.ViewModels.SizeViewModel

@Html.Partial("_Message")

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-sm-6 col-xs-10">
        @using (Html.BeginForm("Size Detail"))
        {

            @Html.HiddenFor(m => m.Id)
            <div class="form-group col-md-10">
                @Html.LabelFor(m => m.Name)
                @Html.DisplayFor(m => m.Name)
            </div>
            <div class="form-group col-md-10">
                @Html.LabelFor(m => m.Acronym)
                @Html.DisplayFor(m => m.Acronym)
            </div>

            <div class="form-group col-md-10 mt-4">
                @Html.ActionLink("Go Back", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

TrackingRace/Views/Size/Index.cshtml
@model TrackingRace.ViewModels.SizeListViewModel
@Html.Partial("_Message")

<div class="d-inline-block">
    <h2>@ViewBag.Title</h2>
</div>

<div class="d-inline-block float-right">
    <a href="@Url.Action("Add")" class="btn btn-primary btn">Add</a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            @*<th>Id</th>*@
            <th>Name</th>
            <th></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.Sizes.Count; i++)
        {
            <tr>
                @*<td>@Model.Sizes[i].Id</td>*@
                <td>@Model.Sizes[i].Name</td>
                <td>@Model.Sizes[i].Acronym</td>
                <td>
                    <div class="float-right">

                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="@Url.Action("Edit", new { id = Model.Sizes[i].Id })" class="btn btn-secondary btn-xs margin-right">
                                <span class="hidden-xs"> Edit</span>
                            </a>
                            @*<a href="@Url.Action("Detail", new { id = Model.Sizes[i].Id })" class="btn btn-secondary btn-xs margin-right">
                                <span class="hidden-xs"> Detail</span>
                            </a>*@

                            <a data-toggle="modal" href="@("#deleteSizeModal" + i)" class="btn btn-danger btn-xs margin-right">
                                <span class="hidden-xs"> Delete</span>
                            </a>
                        </div>
                        <div class="modal fade" id="@("deleteSizeModal" + i)" tabindex="-1" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    @using (Html.BeginForm("Delete", "Size"))
                                    {
                                        <input type="hidden" value="@Model.Sizes[i].Id" name="Id" />
                                        <div class="modal-header">
                                            <h4 class="modal-title">Delete @Model.Sizes[i].Name</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete @Model.Sizes[i].Name?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Yes</button>
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>