TrackingRace/ViewModels/RaceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using TrackingRaceLibrary.Models;

namespace TrackingRace.ViewModels
{
    public class RaceViewModel
    {
        public RaceViewModel()
        {
            DateString = Date.ToString("MM/dd/yyyy");
        }

        public int? Id { get; set; }

        [Required(ErrorMessage = "The Name field is required")]
        [Display(Name = "Name:")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required(ErrorMessage = "The Date field is required")]
        [Display(Name = "Date:")]
        [DisplayFormat(DataFormatString = "{MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public string DateString { get; set; }

        [Required(ErrorMessage = "The Race Type is required")]
        [Display(Name = "Race type:")]
        public int RaceTypeId { get; set; }

        [Display(Name = "Profit")]
        public bool Profit { get; set; }

        [Required(ErrorMessage = "The Address field is required")]
        [Display(Name = "Address:")]
        [StringLength(100)]
        public string Address { get; set; }

        [Required(ErrorMessage = "The City field is required")]
        [Display(Name = "City:")]
        [StringLength(20)]
        public string City { get; set; }

        [Required(ErrorMessage = "The State field is required")]
        [Display(Name = "State:")]
        public int StateId { get; set; }

        [Required(ErrorMessage = "The Zip Code field is required")]
        [Display(Name = "Zip Code:")]
        public int ZipCode { get; set; }

        //[Required(ErrorMessage = "The State field is required")]
        //public StateViewModel State { get; set; }

        //[Required(ErrorMessage = "The Race Type field is required")]
        //public RaceTypeViewModel RaceType { get; set; }

        [Display(Name = "State:")]
        public string StateName { get; set; }
        public string StateAcronym { get; set; }

        [Display(Name = "Race Type:")]
        public string RaceTypeName { get; set; }

        public virtual List<RunnerViewModel> Runners { get; set; }
    }
}

TrackingRace/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackingRace.ViewModels;
using TrackingRaceLibrary.Data;
using TrackingRaceLibrary.Models;

namespace TrackingRace.Controllers
{
    public class RaceController : Controller
    {
        private Context _context = null;

        public RaceController()
        {
            _context = new Context();
        }

        private bool _disposed = false;

        protected override void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            if (disposing)
            {
                _context.Dispose();
            }

            _disposed = true;

            base.Dispose(disposing);
        }

        // GET: States
        public ActionResult Index()
        {
            ViewBag.Title = "Work With Races";

            using (var context = new Context())
            {
                var raceList = new RaceListViewModel
                {
                    Races = context.Races.Select(p => new RaceViewModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        Profit = p.Profit,
                        City = p.City,
                        Date = p.Date,
                        StateId = p.StateId,
                        StateName = p.State.Name,
                        StateAcronym = p.State.Acronym,
                        RaceTypeName = p.RaceType.Name,
                        RaceTypeId = p.RaceTypeId
                    }).ToList()
                };
                raceList.TotalRaces = raceList.Races.Count;

                return View(raceList);
            }
            
        }

        //Detail
        public ActionResult Detail(int id)
        {
            //ViewBag.Title = "Detail";
            using (var context = new Context())
            {
                //var restaurant = lunchContext.Restaurants.SingleOrDefault(p => p.RestaurantId == id);
                var race = context.Races.Include("State").Include("RaceType").SingleOrDefault(p => p.Id == id);
                if (race != null)
                {
                    var raceViewModel = new RaceViewModel
                    {
                        Id = race.Id,
                        Name = race.Name,
                        Profit = race.Profit,
                        Address = race.Address,
                        City = race.City,
                        DateString = race.Date.ToShortDateString(),
                        StateId = race.StateId,
                        RaceTypeId = race.RaceTypeId,
                        StateName = race.State.Name,
                        RaceTypeName = race.RaceType.Name,
                        ZipCode = race.ZipCode
                    };

                    ViewBag.Title = "Detail: " + raceViewModel.Name;
                    return View(raceViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        //Add
        public ActionResult Add()
        {
            ViewBag.Title = "Add Race";
            var raceViewModel = new RaceViewModel();

            ViewBag.SelectRaceType = new SelectList(
                _context.RaceTypes, "Id", "Name");

            ViewBag.SelectState = new SelectList(
                _context.States, "Id", "Name");

            raceViewModel.Date = DateTime.Today;

            return View("AddEdit", raceViewModel);
        }
        
        [HttpPost]
        public ActionResult Add(RaceViewModel raceViewModel)
        {

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var race = new Race
                    {
                        Name = raceViewModel.Name,
                        Date = raceViewModel.Date,
                        RaceTypeId = raceViewModel.RaceTypeId,
                        Address = raceViewModel.Address,
                        City = raceViewModel.City,
                        StateId = raceViewModel.StateId,
                        ZipCode = raceViewModel.ZipCode,
                        Profit = raceViewModel.Profit
                    };

                    context.Races.Add(race);
                    context.SaveChanges();
                }

                TempData["Message"] = "Your race was successfully added!";
                return RedirectToAction("Index");
            }

            ViewBag.SelectRaceType = new SelectList(
                _context.RaceTypes, "Id", "Name");

            ViewBag.SelectState = new SelectList(
                _context.States, "Id", "Name");

            return View("AddEdit", raceViewModel);
        }

        public ActionResult Edit(int id)
        {
            using (var context = new Context())
            {
                var race = context.Races.SingleOrDefault(p => p.Id == id);
                if (race != null)
                {
                    var raceViewModel = new RaceViewModel
                    {
                        Id = race.Id,
                        Name = race.Name,
                        Date = race.Date,
                        RaceTypeId = race.RaceTypeId,
                        Address = race.Address,
                        City = race.City,
                        StateId = race.StateId,
                        ZipCode = race.ZipCode,
                        Profit = race.Profit
                    };

                    ViewBag.SelectRaceType = new SelectList(
                        _context.RaceTypes, "Id", "Name");

                    ViewBag.SelectState = new SelectList(
                        _context.States, "Id", "Name");

                    return View("AddEdit", raceViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        [HttpPost]
        public ActionResult Edit(RaceViewModel raceViewModel)
        {
            //ValdateState(stateViewModel);

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var race = context.Races.SingleOrDefault(p => p.Id == raceViewModel.Id);

                    if (race != null)
                    {
                        race.Name = raceViewModel.Name;
                        race.Date = raceViewModel.Date;
                        race.RaceTypeId = raceViewModel.RaceTypeId;
                        race.Address = raceViewModel.Address;
                        race.City = raceViewModel.City;
                        race.StateId = raceViewModel.StateId;
                        race.ZipCode = raceViewModel.ZipCode;
                        race.Profit = raceViewModel.Profit;

                        TempData["Message"] = "This race was successfully updated!";
                        context.SaveChanges();
                        return RedirectToAction("Index");
                    };
                }
            }
            return View(raceViewModel);
        }

        //Delete
        [HttpPost]
        public ActionResult Delete(RaceViewModel raceViewModel)
        {
            using (var context = new Context())
            {
                var race = context.Races.SingleOrDefault(p => p.Id == raceViewModel.Id);
                if (race != null)
                {
                    TempData["Message"] = race.Name + " race was successfully deleted!";
                    context.Races.Remove(race);
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            return new HttpNotFoundResult();
        }
    }
}

TrackingRace/Views/Race/AddEdit.cshtml
@model TrackingRace.ViewModels.RaceViewModel

@Html.Partial("_Message")

@{
    var isEditMode = Model.Id != null;
    ViewBag.Title = isEditMode ? "Edit" : "Add Race";
}

<h2>@ViewBag.Title</h2>


<div class="row">
    <div class="col-sm-12 col-xs-10">
        @using (Html.BeginForm(isEditMode ? "Edit" : "Add", "Race"))
        {
            @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-dismissible alert-danger" })

            @Html.HiddenFor(m => m.Id)

            <div class="form-group">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>

            <div class="form-row">
                <div class="form-group col-md-8">
                    @Html.LabelFor(m => m.RaceTypeId)
                    @Html.DropDownListFor(m => m.RaceTypeId, (SelectList)ViewBag.SelectRaceType, "", new { @class = "form-control" })
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(m => m.Date)
                    @Html.TextBoxFor(m => m.Date, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Address)
                @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(m => m.City)
                    @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(m => m.StateId)
                    @Html.DropDownListFor(m => m.StateId, (SelectList)ViewBag.SelectState, "", new { @class = "form-control" })
                </div>

                <div class="form-group col-md-2">
                    @Html.LabelFor(m => m.ZipCode)
                    @Html.TextBoxFor(m => m.ZipCode, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(m => m.Profit) @Html.DisplayNameFor(m => m.Profit)
                    </label>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">@(isEditMode ? "Save" : "Add")</button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

TrackingRace/Views/Race/Detail.cshtml
@model TrackingRace.ViewModels.RaceViewModel

@Html.Partial("_Message")

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-sm-6 col-xs-10">
        @using (Html.BeginForm("Race Detail"))
        {

            @Html.HiddenFor(m => m.Id)

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.RaceTypeName)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.RaceTypeName)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.Date)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.DateString)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.Address)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.Address)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.City)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.City)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.StateName)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.StateName)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.ZipCode)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.ZipCode)
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-4">
                    @Html.LabelFor(m => m.Profit)
                </div>
                <div class="form-group col-8">
                    @Html.DisplayFor(m => m.Profit)
                </div>
            </div>

            <div class="form-group col-md-10 mt-4">
                @Html.ActionLink("Go Back", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

TrackingRace/Views/Race/Index.cshtml
@model TrackingRace.ViewModels.RaceListViewModel

@Html.Partial("_Message")

<div class="d-inline-block">
    <h2>@ViewBag.Title</h2>
</div>

<div class="d-inline-block float-right">
    <a href="@Url.Action("Add")" class="btn btn-primary btn">Add</a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Race</th>
            <th class="d-none d-md-table-cell">RaceType</th>
            <th class="d-none d-md-table-cell">City</th>
            <th class="d-none d-md-table-cell">State</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody> 
        @for (var i = 0; i < Model.Races.Count; i++)
        {
            <tr>
                <td>@Model.Races[i].Name</td>
                <td class="d-none d-md-table-cell">@Model.Races[i].RaceTypeName</td>
                <td class="d-none d-md-table-cell">@Model.Races[i].City</td>
                <td class="d-none d-md-table-cell">@Model.Races[i].StateName</td>
                <td>
                    <div class="float-right">
                        <div class="btn-group" role="group">
                            <a href="@Url.Action("Edit", new { id = Model.Races[i].Id })" class="btn btn-secondary btn-xs margin-right">
                                <span class="hidden-xs"> Edit</span>
                            </a>
                            <a href="@Url.Action("Detail", new { id = Model.Races[i].Id })" class="btn btn-secondary btn-xs margin-right">
                                <span class="hidden-xs"> Detail</span>
                            </a>
                            <a data-toggle="modal" href="@("#deleteRaceModal" + i)" class="btn btn-danger btn-xs margin-right">
                                <span class="hidden-xs"> Delete</span>
                            </a>
                        </div>

                        <div class="modal fade" id="@("deleteRaceModal" + i)" tabindex="-1" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    @using (Html.BeginForm("Delete", "Race"))
                                    {
                                        <input type="hidden" value="@Model.Races[i].Id" name="Id" />
                                        <div class="modal-header">
                                            <h4 class="modal-title">Delete @Model.Races[i].Name</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete @Model.Races[i].Name?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Yes</button>
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>