TrackingRace/ViewModels/RaceTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TrackingRace.ViewModels
{
    public class RaceTypeViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Type name is required")]
        [Display(Name = "Name:")]
        [StringLength(20)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Distance is required. It must be specified in kilometers")]
        [Display(Name = "Distance (Km):")]
        [Range(1, 42, ErrorMessage = "Please enter a valid number between 1 and 42")]
        public int DistanceKm { get; set; }
    }
}

TrackingRace/Controllers/RaceTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrackingRace.ViewModels;
using TrackingRaceLibrary.Data;
using TrackingRaceLibrary.Models;

namespace TrackingRace.Controllers
{
    public class RaceTypeController : Controller
    {
        // GET: States
        public ActionResult Index()
        {
            using (var context = new Context())
            {
                var raceTypeList = new RaceTypeListViewModel
                {
                    //Convert each RaceType to a RaceTypeViewModel
                    RaceTypes = context.RaceTypes.Select(p => new RaceTypeViewModel
                    {
                        Id = p.Id,
                        Name = p.Name,
                        DistanceKm = p.DistanceKm
                    }).ToList()
                };
                raceTypeList.TotalRaceTypes = raceTypeList.RaceTypes.Count;
                ViewBag.Title = "Work With Race Types";
                return View(raceTypeList);
            }
        }
        
        //Detail
        public ActionResult Detail(int id)
        {
            using (var context = new Context())
            {
                var raceType = context.RaceTypes.SingleOrDefault(p => p.Id == id);
                if(raceType != null)
                {
                    var raceTypeViewModel = new RaceTypeViewModel
                    {
                        Id = raceType.Id,
                        Name = raceType.Name,
                        DistanceKm = raceType.DistanceKm
                    };
                    ViewBag.Title = "Detail " + raceTypeViewModel.Name;
                    return View(raceTypeViewModel);
                };
            }
            return new HttpNotFoundResult();
        }

        //Add
        public ActionResult Add()
        {
            ViewBag.Title = "Add Race Type";
            var raceTypeViewModel = new RaceTypeViewModel();

            return View("AddEdit", raceTypeViewModel);
        }

        [HttpPost]
        public ActionResult Add(RaceTypeViewModel raceTypeViewModel)
        {
            //ValdateState(stateViewModel);

            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var raceType = new RaceType
                    {
                        Name = raceTypeViewModel.Name,
                        DistanceKm = raceTypeViewModel.DistanceKm
                    };

                    context.RaceTypes.Add(raceType);
                    context.SaveChanges();
                }

                TempData["Message"] = "Your state was successfully added!";
                return RedirectToAction("Index");
            }

            return View(raceTypeViewModel);
        }
        

        //Edit
        public ActionResult Edit(int id)
        {
            using (var context = new Context())
            {
                var raceType = context.RaceTypes.SingleOrDefault(p => p.Id == id);
                if (raceType != null)
                {
                    var raceTypeViewModel = new RaceTypeViewModel
                    {
                        Id = raceType.Id,
                        Name = raceType.Name,
                        DistanceKm = raceType.DistanceKm
                    };
                    return View("AddEdit", raceTypeViewModel);
                }
            }
            return new HttpNotFoundResult();
        }

        [HttpPost]
        public ActionResult Edit(RaceTypeViewModel raceTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var context = new Context())
                {
                    var raceType = context.RaceTypes.SingleOrDefault(p => p.Id == raceTypeViewModel.Id);

                    if (raceType != null)
                    {
                        raceType.Name = raceTypeViewModel.Name;
                        raceType.DistanceKm = raceTypeViewModel.DistanceKm;

                        TempData["Message"] = "Your state was successfully updated!";
                        context.SaveChanges();
                        return RedirectToAction("Index");
                    };
                }
            }
            return View(raceTypeViewModel);
        }




        //Delete
        [HttpPost]
        public ActionResult Delete(RaceTypeViewModel raceTypeViewModel)
        {
            using (var context = new Context())
            {
                var raceType = context.RaceTypes.SingleOrDefault(p => p.Id == raceTypeViewModel.Id);
                if (raceType != null)
                {
                    TempData["Message"] = raceType.Name + " state was successfully deleted!";
                    context.RaceTypes.Remove(raceType);
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            return new HttpNotFoundResult();
        }





    }
}

TrackingRace/Views/RaceType/AddEdit.cshtml
@model TrackingRace.ViewModels.RaceTypeViewModel

@Html.Partial("_Message")

@{
    var isEditMode = Model.Id != null;
    ViewBag.Title = isEditMode ? "Edit" : "Add Race Type";
}

<h2>@ViewBag.Title</h2>


<div class="row">
    <div class="col-sm-6 col-xs-10">
        @using (Html.BeginForm(isEditMode ? "Edit" : "Add", "RaceType"))
        {
            @Html.ValidationSummary("The following errors were found:", new { @class = "alert alert-dismissible alert-danger" })

            @Html.HiddenFor(m => m.Id)
            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            </div>
            <div class="form-group col-md-6">
                @Html.LabelFor(m => m.DistanceKm)
                @Html.TextBoxFor(m => m.DistanceKm, new { @class = "form-control col-md-4" })
            </div>

            <div class="form-group col-md-10 mt-4">
                <button type="submit" class="btn btn-primary">@(isEditMode ? "Save" : "Add")</button>
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

TrackingRace/Views/RaceType/Detail.cshtml
@model TrackingRace.ViewModels.RaceTypeViewModel

@Html.Partial("_Message")

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-sm-6 col-xs-10">
        @using (Html.BeginForm("RaceType Detail"))
        {

            @Html.HiddenFor(m => m.Id)
            <div class="form-group col-md-10">
                @Html.LabelFor(m => m.Name)
                @Html.DisplayFor(m => m.Name)
            </div>
            <div class="form-group col-md-10">
                @Html.LabelFor(m => m.DistanceKm)
                @Html.DisplayFor(m => m.DistanceKm)
            </div>

            <div class="form-group col-md-10 mt-4">
                @Html.ActionLink("Go Back", "Index", null, new { @class = "btn btn-secondary" })
            </div>
        }
    </div>
</div>

TrackingRace/Views/RaceType/Index.cshtml
@model TrackingRace.ViewModels.RaceTypeListViewModel

@Html.Partial("_Message")

<div class="d-inline-block">
    <h2>@ViewBag.Title</h2>
</div>

<div class="d-inline-block float-right">
    <a href="@Url.Action("Add")" class="btn btn-primary btn">Add</a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            @*<th>Id</th>*@
            <th>Name</th>
            <th>Km</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 0; i < Model.RaceTypes.Count; i++)
        {
            <tr>
                @*<td>@Model.RaceTypes[i].Id</td>*@
                <td>@Model.RaceTypes[i].Name</td>
                <td>@Model.RaceTypes[i].DistanceKm</td>
                <td>
                    <div class="float-right">
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="@Url.Action("Edit", new { id = Model.RaceTypes[i].Id })" class="btn btn-secondary btn-xs margin-right">
                                <span class="hidden-xs"> Edit</span>
                            </a>
                            @*<a href="@Url.Action("Detail", new { id = Model.RaceTypes[i].Id })" class="btn btn-secondary btn-xs margin-right">
                                    <span class="hidden-xs"> Detail</span>
                                </a>*@

                            <a data-toggle="modal" href="@("#deleteRaceTypeModal" + i)" class="btn btn-danger btn-xs margin-right">
                                <span class="hidden-xs"> Delete</span>
                            </a>
                        </div>
                        <div class="modal fade" id="@("deleteRaceTypeModal" + i)" tabindex="-1" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    @using (Html.BeginForm("Delete", "RaceType"))
                                    {
                                        <input type="hidden" value="@Model.RaceTypes[i].Id" name="Id" />
                                        <div class="modal-header">
                                            <h4 class="modal-title">Delete @Model.RaceTypes[i].Name</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete @Model.RaceTypes[i].Name?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Yes</button>
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>